node.name = emqx@127.0.0.1
node.cookie = emqxsecretcookie

listener.tcp.default = 0.0.0.0:1883
listener.ws.default = 0.0.0.0:8083

dashboard.listeners.http.bind = 0.0.0.0:18083

allow_anonymous = true
